package application.wavefront;

import java.util.ArrayList;

public class Object3D {

	private String name;
	private ArrayList<Vector> vectors;
	private ArrayList<Field> fields;

	public Object3D(String name) {
		this.name = name;
		vectors = new ArrayList<>();
		fields = new ArrayList<>();
	}

	public void addVector(Vector vector) {
		vectors.add(vector);
	}

	public void addField(Field field) {
		fields.add(field);
	}

	public Object3D projectXY() {
		for (Vector vector : vectors) {
			vector.setZ(0);
		}
		return this;
	}

	public Object3D projectXZ() {
		for (Vector vector : vectors) {
			vector.setY(0);
		}
		return this;
	}

	public Object3D projectYZ() {
		for (Vector vector : vectors) {
			vector.setX(0);
		}
		return this;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("# WaveFront *.obj file (generated by CINEMA 4D)\n\n").append("g " + name + "\n");
		for (Vector vector : vectors) {
			builder.append(vector.toString() + "\n");
		}

		builder.append("\n\n");
		for (Field field : fields) {
			builder.append(field.toString() + "\n");
		}
		return builder.toString();
	}
}
