package application.wavefront;

import java.util.ArrayList;

public class Object3D {

	private String name;
	private ArrayList<Vector> vectors;
	private ArrayList<Face> faces;

	public Object3D(String name) {
		this.name = name;
		vectors = new ArrayList<>();
		faces = new ArrayList<>();
	}

	public void addVector(Vector vector) {
		vectors.add(vector);
	}

	public void addFace(Face face) {
		faces.add(face);
	}

	public ArrayList<Vector> getVectors() {
		return vectors;
	}

	public ArrayList<Face> getFaces() {
		return faces;
	}

	public Object3D projectXY() {
		for (Vector vector : vectors) {
			vector.setZ(0);
		}
		return this;
	}

	public Object3D projectXZ() {
		for (Vector vector : vectors) {
			vector.setY(0);
		}
		return this;
	}

	public Object3D projectYZ() {
		for (Vector vector : vectors) {
			vector.setX(0);
		}
		return this;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("# WaveFront *.obj file (generated by CINEMA 4D)\n\n").append("g " + name + "\n");
		for (Vector vector : vectors) {
			builder.append(vector.toString() + "\n");
		}

		builder.append("\n\n");
		for (Face face : faces) {
			builder.append(face.toString() + "\n");
		}
		return builder.toString();
	}
}
